import Script from "next/script";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
export const metadata = {
  title: "Desires Cake and Treat",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.3/font/bootstrap-icons.min.css"
      />
      <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css" />
      <link rel="stylesheet" type="text/css" href="css/font-awesome.min.css" />
      <link rel="stylesheet" type="text/css" href="css/bistro-icons.css" />
      <link rel="stylesheet" type="text/css" href="css/animate.min.css" />
      <link rel="stylesheet" type="text/css" href="css/settings.css" />
      <link rel="stylesheet" type="text/css" href="css/navigation.css" />
      <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" />
      <link rel="stylesheet" type="text/css" href="css/owl.transitions.css" />
      <link rel="stylesheet" type="text/css" href="css/jquery.fancybox.css" />
      <link rel="stylesheet" type="text/css" href="css/zerogrid.css" />
      <link rel="stylesheet" type="text/css" href="css/style.css" />
      <link rel="stylesheet" type="text/css" href="css/loader.css" />
      <link rel="shortcut icon" href="images/favicon.png"></link>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
        rel="stylesheet"
      ></link>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
        rel="stylesheet"
      ></link>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <AppWrapper> */}
        {children}
        {/* </AppWrapper> */}
        <Script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></Script>
        <Script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></Script>
        <Script src="js/jquery-2.2.3.js" type="text/javaScript"></Script>
        <Script src="js/bootstrap.min.js" type="text/javaScript"></Script>
        <Script src="js/jquery.themepunch.tools.min.js"></Script>
        <Script src="js/jquery.themepunch.revolution.min.js"></Script>
        <Script src="js/revolution.extension.layeranimation.min.js"></Script>
        <Script src="js/revolution.extension.navigation.min.js"></Script>
        <Script src="js/revolution.extension.parallax.min.js"></Script>
        <Script src="js/revolution.extension.slideanims.min.js"></Script>
        <Script src="js/revolution.extension.video.min.js"></Script>
        <Script src="js/slider.js" type="text/javaScript"></Script>
        <Script src="js/owl.carousel.min.js" type="text/javaScript"></Script>
        <Script src="js/jquery.parallax-1.1.3.js"></Script>
        <Script src="js/jquery.mixitup.min.js"></Script>
        <Script src="js/jquery-countTo.js"></Script>
        <Script src="js/jquery.appear.js"></Script>
        <Script src="js/jquery.fancybox.js"></Script>
        <Script src="js/functions.js" type="text/javaScript"></Script>
        <Script src="https://code.jquery.com/jquery-3.6.0.min.js"></Script>
        <Script src="path/to/revolution-slider.js"></Script>
      </body>
    </html>
  );
}
